const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={jobs:[],selected:null,version:'',view:'studio',tiktokMode:'manual'};
let toastTimer,polling=false;
function toast(msg,bad=false){$('toast').textContent=msg;$('toast').className='toast'+(bad?' bad':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),7000);}
async function api(path,method='GET',body){const r=await fetch('/api'+path,{method,headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(Array.isArray(d.detail)?d.detail.map(x=>x.msg).join('; '):d.detail||'Request failed');return d;}
async function action(fn){try{await fn();}catch(e){toast(e.message,true);}}
const date=d=>new Date(d).toLocaleString('en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const tag=s=>`<span class="status ${esc(s)}">${esc(s)}</span>`;
function renderJobs(){
 $('job-count').textContent=state.jobs.length;
 $('jobs-list').innerHTML=state.jobs.length?state.jobs.map(j=>`<button class="job-row ${j.id===state.selected?'selected':''}" data-job="${j.id}">${j.artifacts?`<img class="job-thumb" src="${esc(j.artifacts.cover)}" alt="Story cover">`:'<span class="job-thumb">✦</span>'}<span class="job-copy"><strong>${esc(j.script?.title||j.topic)}</strong><small>${date(j.created_at)} · ${j.spec.duration}s target · ${esc(j.mode)}</small></span>${tag(j.status)}</button>`).join(''):'<div class="empty"><div class="empty-art"><span>✦</span></div><h3>A little idea. A whole new world.</h3><p>Your stories will appear here as your agents bring them to life.</p></div>';
 document.querySelectorAll('[data-job]').forEach(el=>el.onclick=()=>action(async()=>{state.selected=el.dataset.job;state.version='';await detail();renderJobs();$('job-detail').scrollIntoView({behavior:'smooth'});}));
}
async function refresh(){state.jobs=await api('/jobs');renderJobs();if(state.selected)await detail();}
async function detail(){
 const j=await api('/jobs/'+state.selected),version=JSON.stringify([j.status,j.events.length,j.publications,j.feedback,j.approved,j.artifacts]);
 if(version===state.version)return;
 if($('job-detail').contains(document.activeElement)&&['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;
 state.version=version;
 const busy=['queued','researching','writing','producing'].includes(j.status);
 const editable=['review','approved','failed'].includes(j.status)&&!j.publications.some(p=>['sending','published','unknown','submitted','remote_error'].includes(p.status));
 $('job-detail').classList.remove('hidden');
 $('job-detail').innerHTML=`<div class="panel-heading"><h2>${esc(j.script?.title||j.topic)}</h2>${tag(j.status)}</div>${j.error?`<p class="error">${esc(j.error)}</p>`:''}<div class="detail-grid"><div>${j.artifacts?`<video controls preload="metadata" poster="${esc(j.artifacts.cover)}" src="${esc(j.artifacts.video)}"></video><p class="muted">${j.artifacts.duration}s · ${esc(j.artifacts.voice)}</p><div class="detail-actions"><a class="button secondary" href="${esc(j.artifacts.video)}" download="story.mp4">↓ MP4</a><a class="button secondary" href="${esc(j.artifacts.kit)}">↓ Publish kit</a></div>`:`<div class="empty"><span class="agent-icon mint">✦</span><h3>${busy?'Your agents are working':'No video yet'}</h3><p>${busy?'The board updates automatically.':'Resolve the error and retry generation.'}</p></div>`}</div><div>
 <div class="detail-actions">${j.status==='review'?'<button id="approve" class="button primary">✓ Approve this video</button>':''}${j.status==='approved'?'<span class="pill">✓ Approved for publication</span>':''}${j.status==='failed'?'<button id="retry" class="button secondary">↻ Retry generation</button>':''}</div>
 ${j.research?`<div class="section-label">RESEARCH NOTES</div><p class="muted">${esc(j.research.summary)}</p><details><summary>Source evidence (${j.research.sources.length})</summary><pre>${esc(JSON.stringify(j.research.sources,null,2))}</pre></details>`:''}
 ${j.script?`<div class="section-label">ENGLISH STORYBOARD</div>${j.script.scenes.map((s,i)=>`<div class="scene"><strong>${i+1} · ${esc(s.heading)}</strong><p>${esc(s.narration)}</p><small class="subtle">${esc(s.visual)}</small></div>`).join('')}${editable?'<details><summary>Edit script & re-render</summary><p class="muted">Editing cancels queued posts and requires a new approval. Live re-renders call paid image and voice APIs.</p><textarea id="script-editor" class="editor-text"></textarea><button id="save-script" class="button secondary">Save & re-render</button></details>':''}`:''}
 ${j.status==='approved'?`<div class="section-label">PUBLICATION QUEUE</div><form id="publish-form" class="publish-form"><div class="form-row"><div><label>Destination</label><select id="publish-platform">${j.spec.platforms.map(p=>`<option value="${p}">${p==='youtube'?'YouTube':'TikTok'}</option>`).join('')}</select></div><div><label>Visibility / consent</label><select id="publish-privacy"><option value="private">Private (YouTube)</option><option value="unlisted">Unlisted (YouTube)</option><option value="public">Public / TikTok automatic</option></select></div></div><div id="tiktok-options" class="hidden"><label>TikTok publishing</label><select id="publish-tiktok-mode"><option value="manual">Download kit — manual</option><option value="buffer">Buffer — automatic</option></select><p class="muted">Buffer mode uploads this approved MP4 to a public Cloudinary URL, then submits an automatic TikTok post. Select Public to confirm. Manage submitted posts in Buffer.</p></div><label>Run at (local time, optional)</label><input id="publish-date" type="datetime-local"><p class="muted">Blank runs on the next queue check. Keep the server running. ${j.mode==='demo'?'Demo never uploads to external accounts.':'YouTube uses Google OAuth. Buffer submissions allow at least a minute for video ingestion.'}</p><button class="button primary">Add to queue ↗</button></form>`:''}
 ${j.publications.map(p=>`<div class="publication"><strong>${esc(p.platform)}</strong> ${tag(p.status)}<p>${date(p.scheduled_at)} · ${esc(p.result?.message||p.privacy)}${p.result?.url?` · <a class="text-link" href="${esc(p.result.url)}" target="_blank" rel="noopener">Open provider ↗</a>`:''}</p>${p.status==='queued'?`<button class="mini-button" data-cancel="${p.id}">Cancel schedule</button>`:''}${p.provider==='buffer'&&['submitted','published','remote_error'].includes(p.status)?`<button class="mini-button" data-sync="${p.id}">Check Buffer status</button>`:''}</div>`).join('')}
 ${['review','approved'].includes(j.status)?`<details><summary>Performance feedback ${j.feedback?'✓ saved':''}</summary><p class="muted">Real metrics guide future scripts.</p><form id="feedback-form"><div class="form-row"><div><label>Views</label><input id="feedback-views" type="number" min="0" required value="${j.feedback?.views??0}"></div><div><label>Retention (%)</label><input id="feedback-retention" type="number" min="0" max="100" step="0.1" required value="${j.feedback?.retention??0}"></div></div><label>What worked / what to improve</label><textarea id="feedback-note" rows="3" maxlength="1500">${esc(j.feedback?.note||'')}</textarea><button class="button secondary">Save feedback</button></form></details>`:''}
 <div class="section-label">AGENT ACTIVITY</div><ul class="timeline">${j.events.slice().reverse().map(e=>`<li><time>${date(e.created_at)}</time><strong>${esc(e.stage)}</strong> · ${esc(e.message)}</li>`).join('')}</ul></div></div>`;
 if($('script-editor'))$('script-editor').value=JSON.stringify(j.script,null,2);
 if($('approve'))$('approve').onclick=()=>action(async()=>{await api(`/jobs/${j.id}/approve`,'POST');toast('Approved. You can now queue publication.');await refresh();});
 if($('retry'))$('retry').onclick=()=>action(async()=>{await api(`/jobs/${j.id}/retry`,'POST');await refresh();});
 if($('save-script'))$('save-script').onclick=()=>action(async()=>{let s;try{s=JSON.parse($('script-editor').value);}catch{throw new Error('Script must be valid JSON.');}await api(`/jobs/${j.id}/script`,'PUT',s);toast('Rendering the updated story.');document.activeElement.blur();await refresh();});
 if($('publish-form')){
   $('publish-tiktok-mode').value=state.tiktokMode;
   const showTikTok=()=>$('tiktok-options').classList.toggle('hidden',$('publish-platform').value!=='tiktok');
   $('publish-platform').onchange=showTikTok;showTikTok();
   $('publish-form').onsubmit=e=>{e.preventDefault();action(async()=>{const t=$('publish-date').value;await api(`/jobs/${j.id}/publish`,'POST',{platform:$('publish-platform').value,tiktok_mode:$('publish-tiktok-mode').value,privacy:$('publish-privacy').value,scheduled_at:t?new Date(t).toISOString():null});toast('Publication queued.');document.activeElement.blur();await refresh();});};
 }
 if($('feedback-form'))$('feedback-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api(`/jobs/${j.id}/feedback`,'POST',{views:Number($('feedback-views').value),retention:Number($('feedback-retention').value),note:$('feedback-note').value});toast('Feedback saved.');document.activeElement.blur();await refresh();});};
 document.querySelectorAll('[data-cancel]').forEach(el=>el.onclick=()=>action(async()=>{await api(`/publications/${el.dataset.cancel}/cancel`,'POST');await refresh();}));
 document.querySelectorAll('[data-sync]').forEach(el=>el.onclick=()=>action(async()=>{await api(`/publications/${el.dataset.sync}/sync`,'POST');toast('Buffer status updated.');await refresh();}));
}
async function sources(){const list=await api('/sources');$('sources-list').innerHTML=list.length?list.map(s=>`<div class="source-card"><button data-delete="${s.id}">Remove</button><strong>${esc(s.title)}</strong><p>${esc(s.platform)} · ${s.views.toLocaleString()} views · ${date(s.published_at)}</p><p>${esc(s.summary)}</p><a class="text-link" href="${esc(s.url)}" target="_blank" rel="noopener">Open source ↗</a></div>`).join(''):'<p class="muted">No sources yet. Add links to guide your agent.</p>';document.querySelectorAll('[data-delete]').forEach(el=>el.onclick=()=>action(async()=>{await api('/sources/'+el.dataset.delete,'DELETE');await sources();}));}
async function skills(){const list=await api('/skills');$('skills-list').innerHTML=Object.entries(list).map(([n,b],i)=>`<section class="panel"><div class="panel-heading"><h2>${['Trend scout','Story architect','Visual maker','Channel pilot'][i]}</h2><span class="pill">${i<2?'Editable':'Workflow reference'}</span></div><textarea id="skill-${n}" class="skill-editor" ${i>1?'readonly':''}>${esc(b)}</textarea>${i<2?`<button class="button secondary" data-skill="${n}">Save instructions</button>`:''}</section>`).join('');document.querySelectorAll('[data-skill]').forEach(el=>el.onclick=()=>action(async()=>{await api('/skills/'+el.dataset.skill,'PUT',{body:$('skill-'+el.dataset.skill).value});toast('Instructions saved for future jobs.');}));}
async function settings(){
 const s=await api('/settings');
 state.tiktokMode=s.tiktok_publisher==='buffer'?'buffer':'manual';
 $('mode-pill').textContent='● '+(s.mode==='demo'?'Demo':'Live')+' workspace';
 $('mode-banner').textContent=s.mode==='demo'?'Demo mode · Try the workflow without API keys. Videos use sample illustrations and silent audio; nothing is posted externally.':'Live mode · Paid APIs generate scripts, images and English voice. Review before publishing.';
 $('cost-note').textContent=s.mode==='demo'?'Demo generation uses no paid APIs.':'Paid provider usage is separate from ChatGPT Plus.';
 document.querySelector('#sources .banner').textContent='YouTube research uses its API when configured. TikTok research uses optional Apify metadata or imported sources. Metadata is not a watched video; trends need repeated observations.';
 const cards=[
  ['OpenAI',s.connections.openai,s.content_model+' · '+s.image_model],
  ['YouTube research',s.connections.youtube_research,'Video metadata from the last 7 days'],
  ['TikTok research',s.connections.tiktok_research,'Optional Apify keyword discovery · third-party metadata'],
  ['YouTube upload',s.connections.youtube_upload,'OAuth credentials · defaults to private'],
  ['ElevenLabs',s.connections.elevenlabs,'Current voice provider: '+s.tts_provider],
  ['TikTok via Buffer',s.connections.tiktok,'Default: '+state.tiktokMode+' · automatic mode uses public Cloudinary media hosting'],
  ['Channel language',true,'English scripts, voice, prompts, titles and hashtags']
 ];
 $('settings-list').innerHTML=cards.map(([n,on,note])=>`<section class="panel"><div class="panel-heading"><h2>${esc(n)}</h2><span class="pill">${on?'Configured':'Not connected'}</span></div><p class="muted">${esc(note)}</p></section>`).join('');
}
document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>action(async()=>{state.view=el.dataset.view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==state.view));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===el));$('view-title').textContent=el.querySelector('span').textContent;if(state.view==='sources')await sources();if(state.view==='skills')await skills();if(state.view==='settings')await settings();}));
document.querySelectorAll('[data-prompt]').forEach(el=>el.onclick=()=>{$('topic').value=el.dataset.prompt;$('topic').focus();});
$('create-form').onsubmit=e=>{e.preventDefault();action(async()=>{const platforms=['youtube','tiktok'].filter(p=>$(p).checked);if(!platforms.length)throw new Error('Select at least one channel.');$('create-button').disabled=true;try{const j=await api('/jobs','POST',{topic:$('topic').value,audience:$('audience').value,duration:Number($('duration').value),platforms});state.selected=j.id;state.version='';await refresh();toast('Your agents are on it. The board updates automatically.');}finally{$('create-button').disabled=false;}});};
$('source-form').onsubmit=e=>{e.preventDefault();action(async()=>{await api('/sources','POST',{platform:$('source-platform').value,url:$('source-url').value,title:$('source-title').value,summary:$('source-summary').value,views:Number($('source-views').value),published_at:new Date($('source-date').value).toISOString()});toast('Source saved.');$('source-form').reset();await sources();});};
$('refresh').onclick=()=>action(refresh);
action(async()=>{await settings();await refresh();});
setInterval(async()=>{if(document.hidden||state.view!=='studio'||polling)return;polling=true;try{await refresh();}catch{}finally{polling=false;}},3000);
